<php die( 'Restricted access' ); ?>
;
; created by EventsConfig at Mon, 23 Jun 2008 23:57:46 -0400
; Please do not edit
;
com_componentname=com_events
com_adminmail=your@example.com
com_starday=1
com_adminlevel=1
com_mailview=1
com_frontendPublish=6
com_byview=1
com_earliestyear=2007
com_latestyear=2010
com_hitsview=1
com_repeatview=1
com_showrepeats=1
com_linkcloaking=1
com_hideshowbycats=0
com_copyright=0
com_dateformat=1
com_calUseIconic=1
com_navbarcolor=green
com_startview=view_month
com_defColor=category
com_calSimpleEventForm=0
com_calForceCatColorEventForm=0
com_blockRobots=1
com_legacyEvents=1
com_calEventListRowsPpg=15
com_calUseStdTime=1
com_calCutTitle=20
com_calMaxDisplay=5
com_calDisplayStarttime=1
com_calViewName=default
com_enableToolTip=1
com_calTTBackground=1
com_calTTPosX=RIGHT
com_calTTPosY=BELOW
com_calTTShadow=1
com_calTTShadowX=0
com_calTTShadowY=0
com_rss_cache=0
com_rss_cache_time=2500
com_rss_count=10
com_rss_title=Arthur Mcniel
com_rss_description=Arthur Mcniel
com_rss_limit_text=1
com_rss_text_length=25
modcal_DispLastMonth=NO
modcal_DispLastMonthDays=0
modcal_DispNextMonth=NO
modcal_DispNextMonthDays=0
modcal_LinkCloaking=0
modlatest_MaxEvents=5
modlatest_Mode=0
modlatest_Days=20
modlatest_DispLinks=1
modlatest_NoRepeat=0
modlatest_DispYear=0
modlatest_DisDateStyle=0
modlatest_DisTitleStyle=0
modlatest_LinkToCal=0
modlatest_LinkCloaking=0
modlatest_CustFmtStr=${eventDate}[!a: - ${endDate(%I:%M%p)}]<br />${title}
modlatest_RSS=1
